version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: renderuser
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD} # Render の環境変数を利用
      POSTGRES_DB: myapp_production
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d myapp_production -U renderuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle install && bundle exec rails db:prepare && rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
    environment:
      DATABASE_URL: ${DATABASE_URL} # Render の環境変数を利用
    depends_on:
      db:
        condition: service_healthy