services:
  - type: web
    name: my-mvp
    env: ruby
    buildCommand: "./bin/rails assets:precompile"
    startCommand: "./bin/rails server"
    preDeployCommand: "bundle exec rails db:migrate"
