default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  username: <%= ENV["DATABASE_USER"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "password" %>

development:
  <<: *default
  database: myapp_development
  host: db

test:
  <<: *default
  database: myapp_test
  host: db

production:
  main:
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    url: <%= ENV["QUEUE_DATABASE_URL"] || ENV["DATABASE_URL"] %>

