default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  username: <%= ENV["DATABASE_USER"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "password" %>

development:
  <<: *default
  database: myapp_development
  host: db

test:
  <<: *default
  database: myapp_test
  host: db

production:
  main:
    <<: *default
    database: <%= ENV["MAIN_DATABASE_NAME"] || "myapp_production" %>

  queue:
    <<: *default
    database: <%= ENV["QUEUE_DATABASE_NAME"] || "queue_production" %>
